### ISSUE TITLE
GGML_ASSERT: /mnt/build_nv20_cuda_120_b1743/_deps/llama-src/ggml-cuda.cu:226: !"CUDA error" 

### ISSUE THREAD

**Issue by jaykchen** [second-state/LlamaEdge#83]
### Summary

cuda 12.1 and nvcc installed normally

```
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 530.30.02              Driver Version: 530.30.02    CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                  Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA A10G                     On | 00000000:00:1E.0 Off |                    0 |
|  0%   19C    P8               15W / 300W|      0MiB / 23028MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Mon_Apr__3_17:16:06_PDT_2023
Cuda compilation tools, release 12.1, V12.1.105
Build cuda_12.1.r12.1/compiler.32688072_0
```
server starts:
```
 wasmedge --dir .:. --nn-preload default:GGML:AUTO:llama-2-7b-chat.Q5_K_M.gguf llama-api-server.wasm -c 2048  -p llama-2-chat -m Llama-2-7B-Chat
[INFO] Socket address: 0.0.0.0:8080
[INFO] Model name: Llama-2-7B-Chat
[INFO] Model alias: default
[INFO] Prompt context size: 2048
[INFO] Number of tokens to predict: 1024
[INFO] Number of layers to run on the GPU: 100
[INFO] Batch size for prompt processing: 512
[INFO] Temperature for sampling: 0.8
[INFO] Penalize repeat sequence of tokens: 1.1
[INFO] Prompt template: Llama2Chat
[INFO] Log prompts: false
[INFO] Log statistics: false
[INFO] Log all information: false
[INFO] Starting server ...
ggml_init_cublas: GGML_CUDA_FORCE_MMQ:   no
ggml_init_cublas: CUDA_USE_TENSOR_CORES: yes
ggml_init_cublas: found 1 CUDA devices:
  Device 0: NVIDIA A10G, compute capability 8.6, VMM: yes
[INFO] Listening on http://0.0.0.0:8080
```
errors out when query hits:

```
CUDA error: the provided PTX was compiled with an unsupported toolchain.
  current device: 0, in function ggml_cuda_op_flatten at /mnt/build_nv20_cuda_120_b1743/_deps/llama-src/ggml-cuda.cu:7971
  cudaGetLastError()
GGML_ASSERT: /mnt/build_nv20_cuda_120_b1743/_deps/llama-src/ggml-cuda.cu:226: !"CUDA error"
Aborted (core dumped)
```

**Comment by jaykchen** [comment]
updated cuda from 12.1 to 12.2, issue solved

**Comment by hydai** [comment]
Hi @jaykchen 
Thanks for this. We are using CUDA 12.2 to build the plugin, which is the same as the [llama.cpp's default support version](https://github.com/ggerganov/llama.cpp/releases/tag/b1879).
However, it looks like there is no way to run on an older driver version which is smaller than `535.54.03+`. Ref: https://docs.nvidia.com/deploy/cuda-compatibility/index.html#use-the-right-compat-package

We may need to figure out which is the most compatible version of CUDA that is shipped by default.
